name: BOM Release

on:
  workflow_dispatch:
    inputs:
      releaseTicket:
        type: string
        description: 'Enter the Release ticket number'
        required: true
      releaseNotes:
        type: string
        description: 'Enter the Release note'
        required: true

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
  GH_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

jobs:
  release:
    environment: publishing_gradle_config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v3
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/android-repository-setup
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Release Catalog
        working-directory: source
        run: |
          ../sdk-automation-scripts/scripts/android/single-module-release.main.kts bill-of-material bom ${{ github.event.inputs.releaseTicket }} true true ${{ github.event.inputs.releaseNotes }} bill-of-material